### ISSUE TITLE
Create designs for MVP

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#1]
An admin needs to:
- Manage **client projects**
- Manage **open source projects**
- Create **activity**
- See a monthly report to know how much to pay out to whom.
## Client project (serves as a template for the month)
- name
- active
### Client Work Month
- Month
- Number of hours
- OS projects used
- rate (derived from OS projects used)
- total (derived from rate \* people)
## Core OS Royalty Pot Month
- OS project distributions
## Open Source Project (serves as a template for the month)
- name
- active
### Open Source Month
- openSourceProjectId
- significance - can change over time
- isCommissioned
## Activity
- openSourceProjectMonthId
- contributorId
- points
- link or text
## People
- email
- active
### Flow to OS projects and OS Pot

![2_0_key](https://cloud.githubusercontent.com/assets/78602/16699624/d8e7e508-451a-11e6-83b2-6a61501ee17e.png)
### Flow to contributors

![2_0_key](https://cloud.githubusercontent.com/assets/78602/16699635/f3e204b0-451a-11e6-9860-8521c707521d.png)

**Comment by tomgreever** [comment]
Ok, so what if the list of projects under the Client name is collapsed by default and can be expanded? This keeps the interface simpler and allows for 20+ projects. Since the list of projects a client uses is unlikely to change frequently I think it's ok that it requires an extra step. 

![screen shot 2016-07-18 at 3 04 58 pm](https://cloud.githubusercontent.com/assets/326843/16928627/421e05e4-4cf9-11e6-8bf4-aab7ae330e77.png)

**Comment by tomgreever** [comment]
For People, what if by default we only show active people. Unchecking them marks them as Inactive and removes them from the list. There could be a "Show Inactive" that reveals them again in case they need to be added back. 

![people](https://cloud.githubusercontent.com/assets/326843/16929223/57f15256-4cfc-11e6-9cdf-ae986ca45625.gif)

**Comment by justinbmeyer** [comment]
@tomgreever Open Source Projects should really come before client work.  The client work rate is determined by which os projects are selected (which is determined by the list of os projects).

**Comment by justinbmeyer** [comment]
Also, the @tomgreever the "Core OS Royalty Pot Month" isn't taken into account for these designs.

**Comment by tomgreever** [comment]
@justinbmeyer what about this for the Contributions: 
- by default, last month's projects are added to the current month but without contributor's names
- each project is added by choosing it from the dropdown and clicking "enter contributions"
- The project title shows the total amount available for that project and what's left to be distributed based on any contributions already entered. 
- for each project, multiple contributors can be added by choosing the name from the dropdown
- Remove contributors by clicking X on the right

<img width="956" alt="screen shot 2016-07-19 at 8 02 43 am" src="https://cloud.githubusercontent.com/assets/326843/16957710/22ee990e-4da3-11e6-8fb5-e06e992e5a79.png">

**Comment by tomgreever** [comment]
And then I immediately realized that both "Projects" and "Contributions" could be combined into one interface like this: 
<img width="937" alt="screen shot 2016-07-19 at 12 25 35 pm" src="https://cloud.githubusercontent.com/assets/326843/16957809/932831f8-4da3-11e6-9d53-680be63c95f0.png">

**Comment by tomgreever** [comment]
So here's a basic overall wireframe of where we're at: 
<img width="987" alt="screen shot 2016-07-19 at 12 33 17 pm" src="https://cloud.githubusercontent.com/assets/326843/16958070/a0a1a2d2-4da4-11e6-9c73-9171ebe705e3.png">
<img width="923" alt="screen shot 2016-07-19 at 12 33 25 pm" src="https://cloud.githubusercontent.com/assets/326843/16958077/a7b4a808-4da4-11e6-9345-80ba1fa2d9cf.png">

@justinbmeyer I need to better understand the Core OS Pot. How is that number calculated? Who (where) does it get paid to?

**Comment by justinbmeyer** [comment]
I would prefer we keep them seperate b/c they are going to be worked on at different times (the projects and their significance won't change much)

**Comment by justinbmeyer** [comment]
Also, the "available" stuff doesn't really work out.  If there were 10 combined points from all previous month, and 1000 points contributed this month, 99% of the current month's revenue would go to people who contributed this month.
