### ISSUE TITLE
OS Project component does not display name

### ISSUE THREAD

**Issue by ilyavf** [donejs/bitcentive#105]
![image](https://cloud.githubusercontent.com/assets/1895948/20276363/eba07426-aa69-11e6-847e-b004dda3d461.png)

**Comment by ilyavf** [comment]
This is because we do: `osProjects.get( {_id: 1234} )` and not ` .get( 1235 )`

If #26 PR is merged then it will allow to pass `_id` inside params object.

**Comment by justinbmeyer** [comment]
shows up for me ... fixed now?
