### ISSUE TITLE
Cannot use $populate to get the ref data

### ISSUE THREAD

**Issue by ilyavf** [donejs/bitcentive#106]
E.g.: `public/components/contribution-month/contribution-month.js`

With the current `can-connect-feathers` when we try to retrieve one item we have to do:
```js
ContributionMonth.get( this.contributionMonthId );
```

There is no way to pass extra params, like `$populate=osProjectRef`. Feathers's method `get` expects the 1st argument as `id` and the rest as the params (which should work).

What we probably want to do from app is:
```js
ContributionMonth.get( this.contributionMonthId, {$populate: "osProjectRef"} );
```
or
```js
ContributionMonth.get({
    _id: this.contributionMonthId, 
    $populate: "osProjectRef"
});
```

**Comment by justinbmeyer** [comment]
We should only support the second option:

ContributionMonth.get({
    _id: this.contributionMonthId, 
    $populate: "osProjectRef"
});

**Comment by ilyavf** [comment]
The following works:
```js
ContributionMonth.get({
    _id: this.contributionMonthId,
    query: {'$populate': ['monthlyOSProjects.osProjectRef']}
});
```
Still requires the following change for [can-connect-feathers PR 26](https://github.com/canjs/can-connect-feathers/pull/26).

**Comment by BigAB** [comment]
Now that https://github.com/canjs/can-connect-feathers/pull/26 has been merged, is this still an issue?
