### ISSUE TITLE
Validate sessions against Github

### ISSUE THREAD

**Issue by DesignByOnyx** [donejs/bitcentive#114]
While attempting to test #55, I removed Bitcentive from my Github **Settings -> "Authorized applications"**. Upon refreshing the Bitcentive app I expected my session to be validated against Github, thus logging me out due to revoked access.

**Comment by marshallswain** [comment]
Yep, it's just validating the JWT on refresh.  Validation against GitHub only happens when the JWT is created.

**Comment by marshallswain** [comment]
Also, I don't think the current version of feathers-authentication is flexible enough to make this an easy thing to do.  The good news is that version 1.0.0-alpha was released yesterday, and that version should be flexible enough to do whatever you want to do.  I still haven't tested it out, yet, but there are a few working examples in the repo.

**Comment by justinbmeyer** [comment]
@DesignByOnyx why would you expect this on refreshing?  I would imagine it would only happen the next time you tried to authenticate.

**Comment by DesignByOnyx** [comment]
I mainly put this here for visibility. It seems like a reasonable thing to validate the session from time to time, especially once during the startup of an SPA. It can be closed if we think it's not an issue or not a problem we want to fix. Maybe it's better suited for feathers-auth.
