### ISSUE TITLE
Update feathers-authentication to 1.0

### ISSUE THREAD

**Issue by BigAB** [donejs/bitcentive#132]
Upgrading to the `@next` version breaks the app right now

We shoudl figure out what will be needed to do to upgrade to 1.0 for all the `feathers-authentication` related packages

**Comment by marshallswain** [comment]
I believe this will fix #112

**Comment by marshallswain** [comment]
This is finished and deployed.  https://github.com/donejs/bitcentive/commit/70b748dfc9e2a36fd13b3629bd9d1b664fb07003
