### ISSUE TITLE
Can-Component template is deprecated warning

### ISSUE THREAD

**Issue by BigAB** [donejs/bitcentive#134]
When using the latst can-component, you get this deprecated warning in the console:

![image](https://cloud.githubusercontent.com/assets/76821/20635569/600755ce-b324-11e6-9001-6436bc4c02e1.png)
 > can-component.prototype.template: is deprecated and will be removed in a future release. Use can-component.prototype.view

**Other Repos**
- [ ] https://github.com/icanjs/auth-component/issues/16
- [ ] https://github.com/donejs/done-component/issues/20

**Comment by marshallswain** [comment]
This is still an issue: 
![screen shot 2016-12-16 at 11 23 38 pm](https://cloud.githubusercontent.com/assets/128857/21284915/dde23f7c-c3e6-11e6-8cae-937cb7fc1ab7.jpg)
