### ISSUE TITLE
contributions: OS dropdown does not show the same list of items as the rest.

### ISSUE THREAD

**Issue by ilyavf** [donejs/bitcentive#153]
E.g. 
- contributions dropdown shows 5 items
- OS table: 7 items

contributions.js:
```
  osProjects: {
    get() {
      return OSProject.getList({});
    }
  }
```

**Comment by BigAB** [comment]
@ilyavf I can't reproduce this, can you give me some instructions on how to make this happen?

**Comment by ilyavf** [comment]
Fixed with 
https://github.com/donejs/bitcentive/pull/156
