### ISSUE TITLE
logout shouldn't redirect to '/'

### ISSUE THREAD

**Issue by ilyavf** [donejs/bitcentive#175]
Open `http://localhost:3030/development.html`

The logout will redirect to `http://localhost:3030/` which resolves with 404 (with no SSR and push-state routing).

**Comment by marshallswain** [comment]
can-connect-feathers should probably do something more like this for destroyData:

```js
destroyData: function (session) {
  return feathersClient.logout().then(function(){
    this.destroyInstance(session);
  }.bind(this));
}
```

Then the "session destroyed" event will fire and clear the session data from the UI.

**Comment by marshallswain** [comment]
Fixed in https://github.com/donejs/bitcentive/commit/3343ce3c696a2aba92992e8d0a3a728f6d98a69d
