### ISSUE TITLE
Setup access control - server-side-security

### ISSUE THREAD

**Issue by marshallswain** [donejs/bitcentive#181]
Work for this is started in the `server-side-security` branch.

- [x] Create a users.component page.
- [x] Create a user management component to add to the users page.  Users and Contributors will be separate entities, for now.  We can link them up with a 1-to-1 relationship later.
- [x] Add the users page to the menu and index.stache. 
- [x] Add an `isAdmin` field to the User model (#241)
- [x] Put an `admin` checkbox next to each user that only admins can toggle.  Make it read-only for others.

- [x] The first person to login should automatically be set up as an `admin`. (#246)
- [x] admins can upgrade other users to admins.
- [x] admins can make changes in the UI.
- [x] UI is read-only for non-admins.

**Comment by marshallswain** [comment]
@justinbmeyer what should non-admins be allowed to access in the app?  Will they have any restrictions in the dashboard page?

**Comment by justinbmeyer** [comment]
@marshallswain non-admins should only be able to read.
