### ISSUE TITLE
Payouts table goes off screen.

### ISSUE THREAD

**Issue by marshallswain** [donejs/bitcentive#192]
The payouts table currently goes off the screen.  It should horizontally scroll.

![screen shot 2016-12-16 at 11 05 06 am](https://cloud.githubusercontent.com/assets/128857/21273155/893b018c-c37f-11e6-86d7-15bad28fbb8b.jpg)

**Comment by justinbmeyer** [comment]
Put total on left, make table scroll horizontally.
