### ISSUE TITLE
models/client-project.js tech debt

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#199]
- [x] Give a name to ClientProject.List
- [x] Why is parseInstanceProp needed?

Do the same thing for:

- [x] - models/os-project.js
- [x] -  models/contributor.js
- [x] - models/client-project.js

**Comment by ilyavf** [comment]
It does not seem that `parseInstanceProp` is needed. Works fine without it.

**Comment by ilyavf** [comment]
PR: https://github.com/donejs/bitcentive/pull/291
