### ISSUE TITLE
Use tooltip / dropdown for a client project's list of open source projects

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#208]
Instead of showing them in the table, create a tooltip or dropdown that shows them all.

<img width="1136" alt="cursor_and_bitcentive" src="https://cloud.githubusercontent.com/assets/78602/21330262/42ee75e4-c602-11e6-939a-a0bb2caff00f.png">

**Comment by marshallswain** [comment]
How about the Multiple Search Selection from SemanticUI Dropdown?  https://github.com/icanjs/semantic-ui-dropdown-canjs
