### ISSUE TITLE
Payouts UI looks odd in this scenario

### ISSUE THREAD

**Issue by marshallswain** [donejs/bitcentive#217]
![screen shot 2016-12-31 at 9 27 22 am](https://cloud.githubusercontent.com/assets/128857/21578393/7b3e2704-cf3b-11e6-8ce8-b55d2a208bf2.jpg)

**Comment by Alfredo-Delgado** [comment]
@marshallswain Could you expound on _this scenario_? Would hiding the Payouts section make sense?

**Comment by marshallswain** [comment]
I think I'd prefer to see the payouts section still but replace the table with a message.  Something like "Add some contributions to calculate payouts",
