### ISSUE TITLE
Payouts Rewrite

### ISSUE THREAD

**Issue by Alfredo-Delgado** [donejs/bitcentive#247]
For Jamie:

- [x] - List of active people with the ability to add a person.

Other things:

- [ ] - Get rid of contributors section

=========

A Contributor's Contribution Month Payout is currently based on a contributor's current monthly contribution and any of their previous monthly contributions.

At this time, inactive contributors and points decay (#161) are not taken into account.

Implementation possibilities:
- instead of dynamically rolling up contributor points from the current and any previous months, have each ContributionMonth instance be self contained
  - materialize the previous month's contribution payouts (roll-up would just be previous month + current month)
  - should a contribution month have a status of "closed out" once its payouts have been rolled up into the next month?
- the contributors list in a MonthlyContribution instance should come from the sum of the previous month's payouts rollup and any new contributions
  - do not block a rolled up contributor from being removed in the current month 
    - removing a contributor from the current contribution month should 
       - preserve their contribution history
       - stop their contribution points from carrying over
       - allow the contributor to become active at a later date without affecting contribution month payout calculations during their absence

**Comment by justinbmeyer** [comment]
To maybe add a little clarity ...

Each `ContributionMonth` should have a `monthlyContributors` list which are the list of available contributors for that month.  Similar to `monthlyOSProjects`, this should be copied when a new month is created.

The payouts should only account for points by active contributors.

**Comment by jamiemccue** [comment]
- Hovering over users would show the edit and delete icons
- Add Contributor slides open the add panel (similar to the other sections)
- Editing opens a modal 
- Delete opens system prompt
- Show point totals and dollar amounts in each cell

![247](https://cloud.githubusercontent.com/assets/381138/26697003/7b346d98-46c5-11e7-884f-b6305bbbf21a.png)

![247-modal](https://cloud.githubusercontent.com/assets/381138/26697030/8b495388-46c5-11e7-8ba2-c05d904f65fd.png)
