### ISSUE TITLE
Remove root/database.json

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#250]
There's a `database.json` in the root folder that should be replaced by everything in `config`.

**Comment by justinbmeyer** [comment]
https://db-migrate.readthedocs.io/en/latest/Getting%20Started/configuration/

**Comment by ilyavf** [comment]
PR: https://github.com/donejs/bitcentive/pull/305

**Comment by imaustink** [comment]
Closed in #305
