### ISSUE TITLE
normalize contribution-month sub-types

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#251]
```
|   |   ├── contribution-month.js
|   |   ├── monthly-client-project.js
|   |   ├── monthly-client-projects-os-project-list.js
|   |   ├── monthly-contributions.js
|   |   ├── monthly-os-project.js
```

a weird mix of plural / singular and list types.

- [ ] - make sure these paths in the guide are updated
- [x] - rename algebras

**Comment by ilyavf** [comment]
@justinbmeyer  Where is the guide located?

**Comment by justinbmeyer** [comment]
https://github.com/donejs/donejs/blob/bitcentive-guide/docs/guides/bitcentive.md

**Comment by ilyavf** [comment]
@justinbmeyer 

The file `monthly-client-projects-os-project-list.js` exports a DefineList `MonthlyClientProjectsOsProjectList` which item is `"#": OSProject.Ref`.

Does not seem right to rename it to smth like `monthly-client-project-os-project.js`.

Any suggestions?

**Comment by justinbmeyer** [comment]
@ilyavf was there a suggestion to name it that?

**Comment by ilyavf** [comment]
@justinbmeyer No. Do u mean its OK to have the current file name?

**Comment by justinbmeyer** [comment]
maybe.  Everything should be consistent though.  That is what is important.

**Comment by justinbmeyer** [comment]
There should be be both `monthly-client-projects-os-project-list` and `monthly-contributions` which both export lists.  Either both should be plural, or both should end with -list.  

Their "debugger" names should match too.

**Comment by ilyavf** [comment]
I propose the following name convention:

- file name: `client-project.js`, `client-projects.js`
- debugger: `ClientProject`, `ClientProjectList`    - to easier separate lists from items
- property export: `ClientProject`, `ClientProjects`   - to match file names.

**Comment by ilyavf** [comment]
actually, maybe it should just be `*s` instead of `*List` everywhere... so that one can copy paste the debugger name to somewhere, or translate it into a file name easier.

**Comment by ilyavf** [comment]
As per disscussion, keeping `*List` in both debugger and export names, and also `-list` in file names.

**Comment by ilyavf** [comment]
PR: https://github.com/donejs/bitcentive/pull/291
