### ISSUE TITLE
Logout button does not work properly

### ISSUE THREAD

**Issue by ilyavf** [donejs/bitcentive#258]
On Logout we do `session.destroy()`, this clears the cookies, however it does not navigate to a login page, and it allows to use the app further.

**Comment by ilyavf** [comment]
This should be fixed in `can-connect-feathers`

**Comment by justinbmeyer** [comment]
Why would this be fixed in can-connect-feathers?  I would think it would be the app view model that changes the page when the session is destroyed.

**Comment by ilyavf** [comment]
There is something wrong in the following line of  can-connect-feathers: https://github.com/canjs/can-connect-feathers/blob/master/session/session.js#L49
```
    ... || tokenData;
``` 
has been added recently and caused several bugs in bitcentive including this one.

**Comment by ilyavf** [comment]
Waiting for this PR https://github.com/canjs/can-connect-feathers/pull/57

**Comment by ilyavf** [comment]
This was actually due to can-connect `callback-once` behavior bug. Fixed with can-connect 1.33

**Comment by ilyavf** [comment]
Tested on heroku OK.
