### ISSUE TITLE
Error: Cannot define property:__v

### ISSUE THREAD

**Issue by ilyavf** [donejs/bitcentive#267]
To reproduce:
- Create a **new client project** OR a **new contribution**.
- Navigate to Contributors page.
- Navigate back to Dashboard.

![image](https://cloud.githubusercontent.com/assets/1895948/22697860/c175276a-ed20-11e6-89e8-52ec2c3aea63.png)

After refreshing the page the app works well.

**Comment by justinbmeyer** [comment]
We should probably just add `seal: false` on our models

**Comment by ilyavf** [comment]
@justinbmeyer I am not sure about not sealing the models... We don't have any usecases to change the defined models. I think we should not just ignore adding the `__v` property. Is there a way to do this?

**Comment by justinbmeyer** [comment]
@ilyavf my reasoning is that we want to be flexible if the service layer changes.  you can always just do `__v: "string"` .

**Comment by ilyavf** [comment]
ok, agree.

**Comment by ilyavf** [comment]
Fixed.
