### ISSUE TITLE
Sometimes the admin page shows everyone as an admin

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#270]
Seems to happen if I navigate between dashboard, users, and contributors enough times:

![cursor_and_bitcentive](https://cloud.githubusercontent.com/assets/78602/22700471/7109cb8c-ed20-11e6-8357-4ca5ad15c290.png)

**Comment by ilyavf** [comment]
Yeah, i can reproduce this! Everybody except for the last Brian becomes an admin.

**Comment by ilyavf** [comment]
In DB not all users have `isAdmin` property.

Initially when you load `users` page:
```js
canViewModel('bit-users').users[3].isAdmin === false
```
but when you navigate off the page and back:
```js
canViewModel('bit-users').users[3].isAdmin === undefined
```

I dont know why 
```
<input type="checkbox" {$checked}="user.isAdmin" ($change)="setAdmin(user, %element.checked)" />
```
shows checked checkbox for `undefined`.

There is a PR with db-migrate to populate all items with `isAdmin`. This will fix the issue.

**Comment by ilyavf** [comment]
Created an issue in `can-stache-bindings` https://github.com/canjs/can-stache-bindings/issues/135

**Comment by ilyavf** [comment]
PR in `can-util`: https://github.com/canjs/can-util/pull/188
