### ISSUE TITLE
Add total to Payout columns.

### ISSUE THREAD

**Issue by pstrozak** [donejs/bitcentive#274]
Under payouts, add total for each column.

<img width="1002" alt="screen shot 2017-02-08 at 11 39 04 am" src="https://cloud.githubusercontent.com/assets/8048755/22749565/683a3a90-edf3-11e6-8aee-fb41ea20898b.png">

**Comment by jamiemccue** [comment]
- Setup a footer with the same green BG as the total column
- Add totals for each column

![274](https://cloud.githubusercontent.com/assets/381138/26742922/a5611eca-4794-11e7-9436-9978b4cee28e.png)
