### ISSUE TITLE
changing an old contribution value breaks the app

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#275]
changing a contribution value makes the app go crazy.  It seems to recover after a refresh.

**Comment by ilyavf** [comment]
@justinbmeyer What change do you mean - description / points ?

I am trying on my local, it behaves normally.

Do I need to do some specific manipulations? For extra, I tried to add a new contribution, navigate back and forth, etc.

**Comment by justinbmeyer** [comment]
A contribution in a

**Comment by justinbmeyer** [comment]
A contribution in an old month.

**Comment by ilyavf** [comment]
I believe this is fixed with the PR for unsealed models https://github.com/donejs/bitcentive/pull/272

**Comment by ilyavf** [comment]
Now any contribution change messes the page: the month selection gets duplicate months and the selected month gets changed.

The issue happens only in prod. I got a dump of db and built locally, the app works fine locally.

@justinbmeyer are the errors silenced on production?

**Comment by ilyavf** [comment]
This will be fixed with `can-connect` PR: https://github.com/canjs/can-connect/pull/257

**Comment by ilyavf** [comment]
Tested on heroku - OK.
