### ISSUE TITLE
Working with dates (ignore timezones)

### ISSUE THREAD

**Issue by ilyavf** [donejs/bitcentive#300]
Current problem is with `select-contribution-month` when creating a new month: instead of the next month the existing month is getting created when user is on < EST (e.g. CST).

In DB we have the `date` stored as `ISODate("2017-02-01T05:00:00.000Z")` so `momentjs` when adding one month to this date and displaying it for CST user shows `Tue Feb 28 2017 23:00:00 GMT-0600 (CST)`

**Comment by ilyavf** [comment]
```js
moment( "2016-09-19T00:00+00:00" ).toDate()
// >>> Sun Sep 18 2016 20:00:00 GMT-0400 (EDT)
```

**Comment by ilyavf** [comment]
The problem is that having the `date` property of native type `Date` we get start of the month with the local timezone. E.g. start of February on my computer (EST) resolves to:
```js
// Lets say my date is Feb 15, so i need Feb 1.
var startFebruary = moment().startOf( "month" ).toDate();
// >>> Wed Feb 01 2017 00:00:00 GMT-0500 (EST)

// We save to DB:
var dateString = JSON.stringify( startFebruary );
// >>> "2017-02-01T05:00:00.000Z"
```
_Note: `T` is followed by time; `Z` in the end means UTC (no timezone, or +00:00)_

Now I am on `CST` and I read `Feb 1 EST` as `January 31 CST`:
```js
var startFebruary = moment( "2017-02-01T05:00:00.000Z" );
// >>> Tue Jan 31 2017 23:00:00 GMT-0600 (CST)
``` 
which is obviously wrong.


==========
**Solutions**

A. Strip time when serializing `date` for saving to DB.

B. Use 2nd day of month as start month date:
      `moment().startOf( "month" ).add( 1, "day" ).toDate()`

C. Use `moment.tz()` with a fixed timezone for everybody instead of just `moment()`:
```js
var moment = require('moment-timezone');

// Setting date:
JSON.stringify( moment().tz("America/Chicago").startOf( "month" ).toDate() )
"2017-02-01T06:00:00.000Z"

// Reading date:
JSON.stringify( moment.tz("2017-02-01T06:00:00.000Z", "America/Chicago").toDate() )
"2017-02-01T06:00:00.000Z"
```

**Comment by marshallswain** [comment]
Solving this in the API layer (Solution A) will give consistent results from any client.  Otherwise, I would think Solution C would give the most consistent results.

**Comment by justinbmeyer** [comment]
> A. Strip time when serializing date for saving to DB.

Do you mean strip __time zone__?

**Comment by BigAB** [comment]
I think you should migrate the db to use UTC time, then convert all API and conversion to use only UTC until displaying for the client, then display in their timeszone.

That,  I think, is the "right way" to do it

**Comment by ilyavf** [comment]
> Do you mean strip time zone?

no, strip time, because we store date in DB without timezone:

>Note: T is followed by time; Z in the end means UTC (no timezone, or +00:00)

**Comment by ilyavf** [comment]
@BigAB 

>I think you should migrate the db to use UTC time

We are storing dates in DB as UTC:
```
ISODate("2016-12-01T07:00:00.000Z")
```

**Comment by justinbmeyer** [comment]
@BigAB "time" is irrelevant in this app ... only "date".  We shouldn't display in the user's timezone, we should just display the date in UTC.

**Comment by ilyavf** [comment]
After a discussion with @justinbmeyer the solution for Bitcentive is to "work" with dates as with UTC dates:

1.  Generating date: `moment.utc().startOf( "month" ).toDate()`
2. Reading date: `moment.utc( dbDateString ).add( 1, "months" ).startOf( "month" ).toDate()`
3. Displaying date: `moment.utc( localDate ).format("MMMM YYYY")`

```js
// 1. Generate start of the month date:

JSON.stringify( moment().startOf('month').toDate() )
"2017-03-01T05:00:00.000Z"     // <<< WRONG

JSON.stringify( moment().utc().startOf('month').toDate() )
"2017-03-01T00:00:00.000Z"    // <<< CORRECT

// 2.  Read date received from DB and generate a new month:

JSON.stringify( moment("2017-02-01T00:00:00.000Z").add( 1, 'months' ).startOf( 'month' ).toDate() )
"2017-02-01T05:00:00.000Z"     // <<< WRONG

JSON.stringify( moment.utc("2017-02-01T00:00:00.000Z").add( 1, 'months' ).startOf( 'month' ).toDate() )
"2017-03-01T00:00:00.000Z"    // <<< CORRECT
```
