### ISSUE TITLE
Show dollar / points for OS Projects

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#313]
On the OS Project's page, it would be nice to show how much $ is paid per project after the total:

<img width="723" alt="cursor_and_bitcentive" src="https://cloud.githubusercontent.com/assets/78602/26599585/a828d272-453e-11e7-81f8-a895e8744182.png">

This can be done by taking the total and dividing it by the number of points in the royalty pot for that projects.

For example, if DoneJS has $250 and 100 current points, then every point is worth $2.50 per month.

**Comment by jamiemccue** [comment]
![313](https://cloud.githubusercontent.com/assets/381138/26696904/3660cc3e-46c5-11e7-8d14-86399f18383a.png)

**Comment by leoj3n** [comment]
* dollar per POINT
