### ISSUE TITLE
Show point totals and dollar amounts in contributions.

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#315]
![cursor_and_bitcentive](https://cloud.githubusercontent.com/assets/78602/26645223/fa569b1a-45fc-11e7-8302-8f449db9e554.png)

For each one of these cells, we should list total points contributed and the dollar amount.

**Comment by jamiemccue** [comment]
- Show point totals and dollar amounts in each cell
- Add total points contributions footer

![315](https://cloud.githubusercontent.com/assets/381138/26697222/10e8d964-46c6-11e7-9b4e-4d88d0961337.png)
