### ISSUE TITLE
Create "Open Source Projects" modlet

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#4]
![home](https://cloud.githubusercontent.com/assets/78602/16930740/2c1d64e2-4d03-11e6-9cfc-e70dd5416221.png)

**Comment by justinbmeyer** [comment]
`<bit-client-project {client-project}/>`

- clientProject - the list of client projects on a contribution-month.

**Comment by Sinjhin** [comment]
This appears to be complete but also see #70
