### ISSUE TITLE
OS project calculation is incorrect

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#45]
<img width="951" alt="localhost_3030_components_contribution-month_contribution-month_html" src="https://cloud.githubusercontent.com/assets/78602/17079953/4fc9b57c-50e5-11e6-810a-0a4017a5302d.png">

CanJS should have $280.

**Comment by garrettreed** [comment]
Could you provide more info for this? I'm seeing what I believe are correct calculations in `staging`.

<img width="710" alt="screen shot 2016-07-23 at 9 48 13 pm" src="https://cloud.githubusercontent.com/assets/4079858/17081270/646f5768-511f-11e6-90ab-56d11d7865bb.png">

**Comment by justinbmeyer** [comment]
I updated staging to be correct. I'll point to the commit tomorrow.

**Comment by justinbmeyer** [comment]
The changes start here: https://github.com/donejs/bitcentive/commit/69ef9da9360a573f4670c8d1cdfdf70fd2d2fa91#diff-aaf60434d5b691c91fb9157e351b5d62R182

There were two bugs.  One was that it wasn't taking into account `commissioned` OS projects in the rate.  Secondly, it wasn't breaking up a client project's total by it's used projects' significance.
