### ISSUE TITLE
Improve tests and code cleanup

### ISSUE THREAD

**Issue by garrettreed** [donejs/bitcentive#51]
- [x] Test coverage needed for contribution month model, specifically the calculations.
  - [x] Test if total for each client project is being calculated properly
  - [x] Test if rate for each client project is being calculated properly
  - [x] Test if total for each OS project is being calculated properly
  - [x] Test if there is no OS project, then the client project calculations return correct value
  - [x] Test if commisioned and uncommissioned toggle is being calculated correctly
- [x] Formatting
- [ ] Commenting

**Comment by obaidott** [comment]
@justinbmeyer: Is there any style guide for code formatting that we need to follow?

**Comment by justinbmeyer** [comment]
generally speaking, I like to follow jQuery's style guide https://contribute.jquery.org/style-guide/js/
