### ISSUE TITLE
Role-based access

### ISSUE THREAD

**Issue by kylegifford** [donejs/bitcentive#56]
Implement role-based access. Need an interface to wrap sections of the code so that only admins can access it.

**Comment by Sinjhin** [comment]
This has a PR #66 that Kyle thinks is close to done.

**Comment by mickmcgrath13** [comment]
I've commented on PR #66.  Long story short, the current roles strategy works as-is but is unconventional for web-based acl.  
The current implementation has an `accessList` on each resource (or resource List).
The other (probably more proper) way to implement would be to have the access list attached to the User or Session.

Thoughts?

**Comment by justinbmeyer** [comment]
closing for #181
