### ISSUE TITLE
Contribution Month component is sometimes not displaying

### ISSUE THREAD

**Issue by Sinjhin** [donejs/bitcentive#68]
![screen shot 2016-09-19 at 11 07 17 am](https://cloud.githubusercontent.com/assets/1085104/18639371/43044432-7e59-11e6-90b4-d0421443b089.png)

**Comment by nlundquist** [comment]
this error seems to occur after adding a new project or contribution

**Comment by DesignByOnyx** [comment]
This was fixed by #119
