### ISSUE TITLE
Get infrastructure setup

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#7]
- [x]  Document development setup
- [x] CI
- [x] CD to firebase / heroku

**Comment by Sinjhin** [comment]
From @mikemitchel:
heroku was working, firebase was sort of working, but manually
I think it had to do with my account being used for some reason
they should be updated/moved to the bitovi accounts for both
I might need to do a transfer for the heroku to bitovi’s user
matthew was doing a bug fix for the firebase issue

**Comment by BigAB** [comment]
I think optimally it would be nice if we worked everything in master, and all merges to master deployed to staging (including firebase hosting for static assets), and only tags deployed to production (production would have it's own firebase hosting deployment for static assets).
