### ISSUE TITLE
Open Source Projects not displaying

### ISSUE THREAD

**Issue by Sinjhin** [donejs/bitcentive#70]
![bitcentive](https://cloud.githubusercontent.com/assets/1085104/18640089/39b91be8-7e5c-11e6-87b4-199068dc1b6a.png)

**Comment by obaidott** [comment]
I am not able to reproduce this issue. Not sure if it is being caused by invalid local cache? 

cc: @BigAB

**Comment by BigAB** [comment]
This probably was caused by a model issue that is now fixed.

Closing
