### ISSUE TITLE
Multiple months getting created

### ISSUE THREAD

**Issue by Sinjhin** [donejs/bitcentive#71]
Bug with month dropdown making duplicate months if it takes a while to loading months from Mongo

![screen shot 2016-09-19 at 11 43 36 am](https://cloud.githubusercontent.com/assets/1085104/18640588/67367208-7e5e-11e6-9fe5-3df9fcdd747b.png)

**Comment by obaidott** [comment]
@Sinjhin I am unable to re-produce this issue. Do you remember how you got that behaviour?

**Comment by DesignByOnyx** [comment]
I'm going to protect against this at the api level. If the client attempts to create an invalid month, an error alert should appear and we can debug from there.
