### ISSUE TITLE
Month dropdown is not changing the data in other components

### ISSUE THREAD

**Issue by Sinjhin** [donejs/bitcentive#77]
When I add a contribution in September, then create October, the same contribution shows up in October.

**Comment by Sinjhin** [comment]
Looks like it might be copying the previous month. Is this a feature?

**Comment by obaidott** [comment]
@justinbmeyer is this the expected behaviour?

cc: @BigAB

**Comment by BigAB** [comment]
@obaidott No, there are certain values that should copy over to a new `contributionMonth` like the OSProject Attributes `commissioned` and `significance`, but contributions should not copy over

**Comment by obaidott** [comment]
Thanks @BigAB
