### ISSUE TITLE
Give monthlyOSProject a reference to its ContributionMonth

### ISSUE THREAD

**Issue by Sinjhin** [donejs/bitcentive#79]
For code cleanup and to allow it to call .save() on the Contribution month rather than itself.

**Comment by BigAB** [comment]
This has a branch https://github.com/donejs/bitcentive/tree/os-projects-cleanup that is almost ready for a PR it just needs:

  - `removeMonthlyOSProject` and `updateComissionedForMonthlyOSProject ` methods added back in to `components/os-projects/os-projects.js` (didn't have time to finish re-write of them
  - fix any references to `models/monthly-contribution.js` (which was de-pluralized)
  - make sure tests run
