### ISSUE TITLE
Use new can-fixture-socket to power demo pages

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/bitcentive#91]
- [ ] - double check that tests are working (or aren't using fixtures).

Problem with socket wanting to connect before fixture module can intercept.

**Comment by justinbmeyer** [comment]
```js
var fixtureSocket = require("can-fixture-socket");

var mockServer = new fixtureSocket.Server(io);

// Mock server behavior
mockServer.on("connection", function(){
  mockServer.emit("notifications", {test: "OK"})
});

System.import("app/models/my-model").then(function(myModel){

});
```



```js
var clone = require("steal-clone"),
      io = require("can-fixture-socket").io;

var mockServer = new fixtureSocket.Server(io);

// Mock server behavior
mockServer.on("connection", function(){
  mockServer.emit("notifications", {test: "OK"})
});


clone({
  "socket.io-client": io
})
```

**Comment by ilyavf** [comment]
By component:
 - [ ] contribution-month
 - [ ] client-projects
 - [ ] contributions
 - [ ] contributors
 - [ ] os-projects
 - [ ] page-dashboard

**Comment by ilyavf** [comment]
The structure of a demo page stays the same. The change needed for `can-fixture-socket` to work with `steal-socket.io` was made in steal: wait till `mainSource` gets loaded.
