### ISSUE TITLE
Figure out how to fixture socket for a demo page

### ISSUE THREAD

**Issue by ilyavf** [donejs/bitcentive#94]
The problem with a demo page like this:
```html
<script can-autorender> … demo template here... </script>
<script src="node_modules/steal/steal.js" main="can-view-autorender">
    require("socket-fixtures");
</script>
```
 is that steal resolves `steal.done()` right after `can-view-autorender` module is loaded. And we need to wait till our demo app is loaded instead (because `steal-socket.io` relies on `steal.done` for resuming socket.io connection).

**Comment by matthewp** [comment]
I think this should work:

```html
<script can-autorender> … demo template here... </script>
<script src="./node_modules/steal/steal.js" main="@empty"></script>
<script>
  steal.import("socket-fixtures").then(function(){
    return steal.import("can-view-autorender");
  });
</script>
```

**Comment by ilyavf** [comment]
Fixed with [this PR](https://github.com/stealjs/steal/pull/917)
